# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Dian's Homepage
description: >- # this means to ignore newlines until "baseurl:"
baseurl: '/dian_web'
url: 'https://dianding0102.github.io'
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publication
    - name: Project

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: dingdian94@sjtu.edu.cn
      link: mailto:dingdian94@sjtu.edu.cn
  follow:
    - name: GitHub
      link: http://github.com/dianding0102
    - name: Scholar
      link: https://scholar.google.com/citations?hl=en&user=rLHI_IcAAAAJ&view_op=list_works&gmla=AJsN-F50apYPdsIa90jZ9PSJdIAM-MS0p77mBtukedgetHbJkXqSO9W4dORS5sCZ941V_GQ-yV9tVzv9jDnCZ7e62X-lC0rIsPIWytGrQFOBhdoCiWq-Z3A

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
