# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Dian's Homepage
description: >- # this means to ignore newlines until "baseurl:"
url: "http://localhost:4000" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publication
    - name: Project

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: dingdian94@sjtu.edu.cn
      link: mailto:dingdian94@sjtu.edu.cn
  follow:
    - name: GitHub
      link: http://github.com/dianding0102

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
